# Numpy Introduction

### Alka Pandey

In [1]:
# Import the numpy package

import numpy as np

In [5]:
# Creating  a numpy array from a list

a1 = np.array([1,3,4,5,6,7,8]) #creating numpy array from a list
print(a1)

[1 3 4 5 6 7 8]


In [6]:
a2 = np.array((1,3,4,5,6,7,8)) #creating numpy array from a tuple
print(a2)

[1 3 4 5 6 7 8]


In [7]:
a3 = np.array({1,3,4,5,6,7,8}) #no error but not recommended because set is unindexed and usage will be a problem later
print(a3)

{1, 3, 4, 5, 6, 7, 8}


In [8]:
type(a1)

numpy.ndarray

In [9]:
type(a2)

numpy.ndarray

In [10]:
type(a3)

numpy.ndarray

In [11]:
a3

array({1, 3, 4, 5, 6, 7, 8}, dtype=object)

In [13]:
a3[2] #indexing is an issue when you create ndarray from set

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [12]:
# Creating  a numpy array from a list with mixed data types

a4 = np.array([1,3,4,5,"ABC",6,7,8]) #creating numpy array from a list
print(a4)

['1' '3' '4' '5' 'ABC' '6' '7' '8']


In [13]:
type(a4[2])

numpy.str_

In [14]:
nn1 = np.array([[3,4,5,6],[7,8,9,8]])
nn1

array([[3, 4, 5, 6],
       [7, 8, 9, 8]])

In [15]:
# creating a multi-dimensional array:

aa1 = np.array([[2,4],[6,7]])
aa1

array([[2, 4],
       [6, 7]])

In [16]:
# create a numpy array by using a list variable

list1 = [5,5,7,8,9,100]
a4 = np.array(list1)
a4

array([  5,   5,   7,   8,   9, 100])

In [18]:
m1 = np.ones(5)
m1

array([1., 1., 1., 1., 1.])

In [19]:
type(m1[1])

numpy.float64

In [20]:
m1.astype(int)

array([1, 1, 1, 1, 1])

In [16]:
z1 = np.zeros((7,7))
z1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
# np.arange(start index,end index,step)

np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [18]:
# creating an array of numbers of a specified range:

arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
z1.shape

(7, 7)

In [20]:
z1.ndim

2

In [21]:
z1.dtype

dtype('float64')

In [22]:
z1.size

49

In [22]:
nn1

array([[3, 4, 5, 6],
       [7, 8, 9, 8]])

In [27]:
nn1[1,2]

9

In [23]:
a2

array([1, 3, 4, 5, 6, 7, 8])

In [30]:
a2[1:5]

array([3, 4, 5, 6])

In [34]:
nn1

array([[3, 4, 5, 6],
       [7, 8, 9, 8]])

In [35]:
nn1[0:2,1:3]

array([[4, 5],
       [8, 9]])

In [37]:
nn1[0:3,1::2]

array([[4, 6],
       [8, 8]])

In [19]:
arr_copy = arr
arr_copy

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
arr_copy2 = np.copy(arr_copy)
print(arr_copy2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
arr = np.arange(10,15)
arr

array([10, 11, 12, 13, 14])

In [26]:
print(arr_copy)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [27]:
print(arr_copy2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [30]:
arr = np.insert(arr,2,1000)

In [31]:
arr

array([  10,   11, 1000,   12,   13,   14])

In [32]:
print(arr_copy)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
print(arr_copy2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [34]:
arr_copy = np.insert(arr_copy,2,99000)
arr_copy

array([   10,    11, 99000,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49])

In [35]:
arr

array([  10,   11, 1000,   12,   13,   14])

In [36]:
# creating a numpy array initialized with all zeros

arr3 = np.zeros((4,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
# creating a numpy array initialized with all ones

arr36 = np.ones((4,4))
arr36

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
# linspace function - returns n equally space numbers between the specified range
#syntax: np.linspace(start_range,end_range,n)

ls = np.linspace(0,100,5)
ls

array([  0.,  25.,  50.,  75., 100.])

In [38]:
# type conversion of list to numpy array
x = [5,67,99]
aaa = np.asarray(x)
aaa

array([ 5, 67, 99])

In [39]:
# type conversion of float values in array to integer
arr3int = arr3.astype(int)
arr3int

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [74]:
# reshaping

arrzero = np.zeros(8)
arrzero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
arr3d = arrzero.reshape((2,2,2))
arr3d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [43]:
arr99 = np.ones(9)
arr3d2 = arr99.reshape((3,3))
arr3d2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
arr3d2.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
aa1.ravel()

array([2, 4, 6, 7])

In [56]:
# slicing
#syntax: slice(start_index,end_index,step)

aapp = np.arange(20)
a_slice = slice(1,15,2)
aapps = aapp[a_slice]
print(aapps)

[ 1  3  5  7  9 11 13]


In [54]:
# accessing elements via index
aapps[3]

7

In [57]:
# other ways of slicing:

print(aapp[4:])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [58]:
# other ways of slicing:

print(aapp[:10])

[0 1 2 3 4 5 6 7 8 9]


In [59]:
# numpy array attributes:

print(aapp.shape)

(20,)


In [60]:
# numpy array attributes:

print(aapp.ndim)

1


In [61]:
# numpy array attributes:

print(aapp.itemsize)

4


In [62]:
aa1.ndim

2

In [38]:
# view demo, create an array a with view and copy

a = np.array([1,4,5,6,7])
a

array([1, 4, 5, 6, 7])

In [40]:
v1 = a.view() #creating a view of array 
v1

array([1, 4, 5, 6, 7])

In [41]:
c = a.copy() #creating a copy of the array
c

array([1, 4, 5, 6, 7])

In [43]:
v1[2] = 100
v1

array([  1,   4, 100,   6,   7])

In [44]:
a #original array changes if you change the view

array([  1,   4, 100,   6,   7])

In [46]:
c[1] = 999
c

array([  1, 999,   5,   6,   7])

In [47]:
a

array([  1,   4, 100,   6,   7])

In [49]:
nn1.mean()

6.25

In [50]:
np.mean(nn1)

6.25

In [24]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
r = np.array([0,1,2])
r

array([0, 1, 2])

In [26]:
c = np.array([0,1,0])
c

array([0, 1, 0])

In [28]:
s = m[r,c]
s

array([1, 5, 7])

In [6]:
import numpy as np
data = np.array([10,14,15,18,21,23,30,35])
data

array([10, 14, 15, 18, 21, 23, 30, 35])

In [7]:
q1 = np.percentile(data,25)
print("Q1:",q1)
q2 = np.percentile(data,50)
print("Q2:",q2)
q3 = np.percentile(data,75)
print("Q3:",q3)

Q1: 14.75
Q2: 19.5
Q3: 24.75


In [9]:
import numpy as np
print(np.__version__)



1.24.3


In [11]:
# Pandas with 'midpoint' method (closer to manual split-halves definition)

import pandas as pd

data = pd.Series([10,14,15,18,21,23,30,35])

q1 = data.quantile(0.25, interpolation="midpoint")
q3 = data.quantile(0.75, interpolation="midpoint")

print("Q1:", q1, "Q3:", q3)


Q1: 14.5 Q3: 26.5


In [12]:
import scipy.stats as stats

In [13]:
z = (0.280-0.295)/0.025

In [14]:
stats.norm.cdf(z)

0.2742531177500741